name: Update Rochester Zoning

on:
  schedule:
    - cron: '0 8 * * *'  # every day at 8AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scripts/update_rochester.py

      - name: Commit and push if updated
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rochester.json
          git commit -m "Auto-update Rochester zoning data" || echo "No changes"
          git push
