name: Update Burnsville Zoning Data

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4
          playwright install

      - name: Run scraper script
        run: python scripts/scrape_burnsville.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git stash --include-untracked
          git pull --rebase origin main
          git stash pop || true
          git add burnsville.json zoning_combined.json
          git commit -m "Update Burnsville zoning data [CI]" || echo "No changes to commit"
          git push
