- name: Commit and push if changed
  env:
    TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
  run: |
    git config --global user.name "zoning-bot"
    git config --global user.email "zoning.bot@protonmail.com"
    git add burnsville.json
    git commit -m "Auto-update Burnsville zoning data" || echo "No changes to commit"
    git push https://$TOKEN@github.com/schadtracysigns/zoning-data.git HEAD:main
